
spring:
  security:
    saml2:
      relyingparty:
        registration:
          okta:
            assertingparty:
              metadata-uri: https://dev-17729161.okta.com/app/exkkfo143htDBx2aV5d7/sso/saml/metadata
            signing:
              credentials:
                - private-key-location: classpath:local.key
                  certificate-location: classpath:local.crt
            singlelogout:
              binding: POST
              response-url: "{baseUrl}/logout/saml2/slo"

---
server:
  tomcat:
    max-http-form-post-size: 10MB
    max-http-header-size: 10MB

